---
- name: Create proxy checker script
  ansible.builtin.template:
    src: apt-proxy-checker.j2
    dest: /usr/local/bin/apt-proxy-checker
    mode: '0775'

- name: Create apt directive configuration
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/00aptproxy
    content: |
      Acquire::Retries 1;
      Acquire::http::ProxyAutoDetect "/usr/local/bin/apt-proxy-checker";
    mode: '0664'

# - name: Create proxy configuration
#   ansible.builtin.copy:
#     dest: /etc/apt/apt.conf.d/00aptproxy
#     content: |
#       Acquire::http::Proxy "{{ apt_proxy_address }}";
#     mode: '0664'

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
