---
- name: Disable IPv6
  ansible.builtin.shell: |
    sysctl net.ipv6.conf.all.disable_ipv6=1

- name: "Modifying GRUB."
  ansible.builtin.shell: |
    sed -i -e "s/GRUB_CMDLINE_LINUX_DEFAULT=\"\(.*\)\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\"/" /etc/default/grub
    update-grub
  when: ansible_distribution_version == "20.04" or ansible_distribution_version == "22.04"


- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Clean cache
  ansible.builtin.apt:
    clean: true

- name: Flush file system buffers
  ansible.builtin.shell: sync

- name: Update file system index
  ansible.builtin.shell: updatedb
