---
- name: Prepare cloud-init
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
    - /etc/cloud/cloud.cfg.d/99-installer.cfg
    - /etc/netplan/00-installer-config.yaml

- name: Write Proxmox cloud-init datasource config
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    content: 'datasource_list: [ConfigDrive, NoCloud]'
  when: ansible_facts['virtualization_type'] == "kvm"

- name: Write vSphere cloud-init datasource config
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    content: 'datasource_list: [ VMware, OVF, None ]'
  when: ansible_facts['virtualization_type'] == "VMware"

- name: Enable VMware customizations
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    line: 'disable_vmware_customization: false'
    state: present
  when: enable_vmware_customizations and ansible_facts['virtualization_type'] == "VMware"

- name: Enable VMware customization scripts
  ansible.builtin.shell: vmware-toolbox-cmd config set deployPkg enable-custom-scripts true
  when: ansible_facts['virtualization_type'] == "VMware"
