---
- name: Set inotify max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "{{ inotify_max_user_watches }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-inotify.conf
    sysctl_set: true
    reload: true
