---
- name: Deploy virtio-multiqueue systemd service
  ansible.builtin.template:
    src: virtio-multiqueue.service.j2
    dest: /etc/systemd/system/virtio-multiqueue.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and start virtio-multiqueue service
  ansible.builtin.systemd:
    name: virtio-multiqueue
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: true
  register: virtio_multiqueue_result

- name: Print virtio-multiqueue service status on failure
  ansible.builtin.command: journalctl -xeu virtio-multiqueue.service --no-pager
  when: virtio_multiqueue_result is failed
  changed_when: false
