---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install additional packages
  ansible.builtin.package:
    name:
      - acl
      - apache2-utils
      - bash-completion
      - ca-certificates
      - cifs-utils
      - curl
      - dialog
      - git
      - iperf3
      - iptables
      - iptables-persistent
      - jq
      - plocate
      - nano
      - neovim
      - net-tools
      - nfs-common
      - p7zip-full
      - plocate
      - python3
      - python3-pip
      - rename
      - rsync
      - screen
      - smbclient
      - tmux
      - tree
      - unattended-upgrades
      - unzip
      - vim
      - wget
      - whois
      - xclip
    state: present
