---
- name: Make sure Python3 and pip3 are installed
  ansible.builtin.package:
    name:
      - python3-full
      - python3-pip
      # - pipx
    state: present

- name: Enable old system packages
  ansible.builtin.shell: |
    python3 -m pip config set global.break-system-packages true
  become: false

# - name: pipx ensurepath
#   ansible.builtin.shell: pipx ensurepath
#   become: false

# - name: pipx completions
#   ansible.builtin.lineinfile:
#     dest: "{{ user_home }}/.bashrc"
#     line: "\n\n#pipx completions\neval \"$(register-python-argcomplete pipx)\"\n"
#     state: present
#     create: true
#     insertafter: EOF
#     mode: '0644'
#   become: false

- name: pip path
  ansible.builtin.lineinfile:
    dest: "{{ user_home }}/.bashrc"
    line: "\n\n#pip\nexport PATH=$PATH:$HOME/.local/bin\n"
    state: present
    create: true
    insertafter: EOF
    mode: '0644'
  become: false

- name: Reload .bashrc
  ansible.builtin.shell: source {{ user_home }}/.bashrc
  become: false
  args:
    executable: /bin/bash
