---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install additional packages
  ansible.builtin.package:
    name:
      - acl
      - bash-completion
      - ca-certificates
      - cifs-utils
      - curl
      - dialog
      - git
      - jq
      - mlocate
      - nano
      - neovim
      - net-tools
      - nfs-common
      - p7zip-full
      - python3
      - python3-pip
      - screen
      - smbclient
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - whois
    state: present

- name: Install Python and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: Install Python Full
  ansible.builtin.package:
    name: python3-full
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Install additional dependencies
  ansible.builtin.pip:
    name: '{{ item }}'
    extra_args: --user
  become: false
  loop:
    - pywinrm
    - pypsrp
    - requests
    - requests-credssp
    - github3.py
    - netaddr
    - dnspython
    - pyvmomi
    - argcomplete
  when: ansible_distribution == "Ubuntu"
