---
- name: Wait for cloud-init
  ansible.builtin.wait_for:
    path: /var/lib/cloud/instance/boot-finished
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Get users home directory
  ansible.builtin.command: echo ~{{ ansible_facts["env"]["SUDO_USER"] | default("root") }}
  register: output

- name: Save user home to variable
  ansible.builtin.set_fact:
    user_home: "{{ output.stdout }}"

- name: Install VM tools
  ansible.builtin.include_tasks: install-vmtools.yml

- name: Disable systemd-networkd-wait-online
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online
    enabled: false
    masked: true
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Configure VirtIO multiqueue
  ansible.builtin.include_tasks: configure-multiqueue.yml
  when: ansible_facts['virtualization_type'] == "kvm"

- name: Install packackes
  ansible.builtin.include_tasks: install-packages.yml

- name: Apply dotfiles
  ansible.builtin.include_tasks: apply-dotfiles.yml

- name: Install pip & pipx
  ansible.builtin.include_tasks: install-python.yml

- name: Configure git
  ansible.builtin.include_tasks: git.yml

- name: Remove snap
  ansible.builtin.include_tasks: remove-snap.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Configure inotify watches
  ansible.builtin.include_tasks: configure-inotify.yml

- name: Clean up system
  ansible.builtin.include_tasks: clean.yml
