#!/bin/bash

# IP address and port of the proxy
IP="192.168.60.4"
PORT="3142"

# Using nc to check if the proxy is accessible
if nc -w1 -z "$IP" "$PORT"; then
    echo "$IP:$PORT"
else
    echo "DIRECT"
fi
